### PR TITLE
feat(speed): better network speed readability

### PR DESCRIPTION
**Pull request by Loongphy**
This PR improves the readability and accuracy of network speed display in the ServerCard component, particularly for lower speed scenarios.

| Before | After |
|--------|-------|
| Before Image | After Image|

### CODE REVIEW

**Comment by hamster1963** [comment]
Thank you for your PR, but in this case, readability may be significantly impacted. Is there a better way to handle this? Thank you.
CleanShot 2024-09-28 at 22 24 54@2x

**Comment by Loongphy** [comment]
> Thank you for your PR, but in this case, readability may be significantly impacted. Is there a better way to handle this? Thank you. CleanShot 2024-09-28 at 22 24 54@2x

The grid layout has been readjusted: `grid-cols-[1fr_1fr_1fr_auto_auto]`, and `gap-1` was set between 768px and 820px to avoid misalignment.

I've done my best 😂

**Comment by hamster1963** [comment]
Thank you very much for your contribution, the original choice of mb units for display was for the sake of overall visual stability, that is, only the numerical part will change, the rest of the part remains stable, at present this improvement may lead to some unstable jitter in the information display part, I will take some more time to understand in detail how to improve this kind of jitter, but always still thank you very much for your contribution!

**Comment by hamster1963** [comment]
After consideration, for the time being, this piece of typography will remain unchanged, and I will consider implementing this requirement in the detail page at a later stage, thank you for your contribution!

**Pull request closed without merging**
