### PR TITLE
improve: ServerCard

### PR DESCRIPTION
**Pull request by kuusei**
1. Modify the ServerCard parameter definition to facilitate future expansion of card information.
2. Change the detailed information from Tooltip to Popover, making it accessible on mobile devices as well.
3. Add detailed information content, with a format inspired by nezha-dashboard.

The details page is not very beautiful, it is acceptable in nezha-dashboard, but it looks a bit ugly here.

### CODE REVIEW

**Comment by hamster1963** [comment]
Thank you for the suggestions. I think the details page still needs some improvements to make it look more suitable. Let’s see what we can do…

> 1. Modify the ServerCard parameter definition to facilitate future expansion of card information.
> 2. Change the detailed information from Tooltip to Popover, making it accessible on mobile devices as well.
> 3. Add detailed information content, with a format inspired by nezha-dashboard.
> 
> The details page is not very beautiful, it is acceptable in nezha-dashboard, but it looks a bit ugly here.

**Comment by kuusei** [comment]
> Thank you for the suggestions. I think the details page still needs some improvements to make it look more suitable. Let’s see what we can do…
> 
> > 1. Modify the ServerCard parameter definition to facilitate future expansion of card information.
> > 2. Change the detailed information from Tooltip to Popover, making it accessible on mobile devices as well.
> > 3. Add detailed information content, with a format inspired by nezha-dashboard.
> > 
> > The details page is not very beautiful, it is acceptable in nezha-dashboard, but it looks a bit ugly here.

I improved the detail style

dimensions: pc
image
dimensions: iphone12
image

**Comment by kuusei** [comment]
I plan to display Load as a circular progress bar later, but currently, there is no reliable way to get the number of CPU cores. 

The NeZha API does not directly provide the number of CPU cores, but it provides CPU information like AMD EPYC 7642 48-Core Processor 2 Virtual Core. 

However, for non-virtualized devices, there should be no * Virtual Core. I'm trying to be compatible with this.

**Comment by hamster1963** [comment]
The new style looks great, but it seems that the content at the top might be obstructed.
CleanShot 2024-07-28 at 22 32 23 2@2x

**Comment by kuusei** [comment]
> The new style looks great, but it seems that the content at the top might be obstructed. CleanShot 2024-07-28 at 22 32 23 2@2x

This seems to happen when the page height is too low when the Popover doesn't have enough space to display (up and down)

image
image

**Pull request merged**
